profileMode:
    enabled: true
    # title: "<Title>" # optional default will be site title
    subtitle: "This is subtitle"
    imageUrl: "archive.png" # optional
    imageTitle: "WarmthDawn's Archive" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
socialIcons: # optional
    - name: "github"
      url: "https://github.com/warmthdawn"
    - name: "email"
      url: "mailto:warmth06@sina.com"

ShowReadingTime: true
ShowCodeCopyButtons: true
ShowBreadCrumbs: true
ShowPostNavLinks: true
mermaid: true
math: true
ShowToc: true